### PR TITLE
Testing tutorial video

### PR DESCRIPTION
**Pull request by saflamini**
@d10r and @sunnyjaycer 

I created a duplicate of the money-streaming-intro project in order to have a demonstration of how to use foundry in our examples.

I also bumped the version on the hardhat money-streaming-intro example because I wanted to show our new process of deploying the framework in a test environment. One that does not need the 'util' folder for the setup script.

Can you guys give this one a look?
1) I know it's not a great practice to have dev versions of dependencies, but I wanted to use it to show what our testing process will soon look like. As soon as 1.4.4 of the ethereum contracts are ready, I will create another PR
2) The foundry example changes nothing in the moneyRouter contract. Just adds a foundry test suite example.

### CODE REVIEW

**Comment by zinderud** [comment]
thank you so much. I am trying to design an integrated application with Superfluid. This will be very useful. especially in my own tests with foundry

**Comment by sunnyjaycer** [comment]
Could use some comments for guidance in test file
https://github.com/superfluid-finance/super-examples/blob/testing-tutorial-video/projects/money-streaming-intro-foundry/test/MoneyRouter.t.sol

You mention "spreaderToken" which isn't relevant for this example (at least I don't think so?)
https://github.com/superfluid-finance/super-examples/blob/testing-tutorial-video/projects/money-streaming-intro/test/MoneyRouter.test.js#L43

In all, I think with money-streaming-intro, you can just make two separate folders inside - one just called "hardhat", and one called "foundry", like...

money-streaming-intro
 |-- hardhat
 |-- foundry

Great stuff! I'll leave another review after running the code.

**Comment by zinderud** [comment]
@sunnyjaycer  https://github.com/superfluid-finance/protocol-monorepo/issues/1152

**Comment by zinderud** [comment]
Yes . Thanks.

**Comment by sunnyjaycer** [comment]
- basic readme for the foundry intro like what's there for the hardhat one could be useful

Might be worth following up with another PR (or at least an issue) for purging the utils folder from the other examples!

Looks good to me!

**Pull request merged**
