### PR TITLE
Employment loan addition

### PR DESCRIPTION
**Pull request by saflamini**
add the borrow-against-streams example

NOTE: this example has been slimmed down substantially to serve as a primitive rather than as a full a comprehensive project

### CODE REVIEW

**Review by JoshuaTrujillo15 — CHANGES_REQUESTED** [review]
# Code Review

## Contracts

Contract functionality looks good.

Please add Natspec to the public variables, external functions + args, events + args, and constructor args per the [Contributing Spec](https://github.com/superfluid-finance/super-examples/blob/3bb818174f8dca18d773fcfeaeada4e3f64b3250/CONTRIBUTING#L44). Internals don't need natspec, though, and no need to remove existing comments.

## Tests

In the test file, the ABI for fDAI is imported from `fDAIABI.js`. However, only the `mint` and `approve` functions are directly called in the script.

I would remove the full `fDAIABI.js` file and instead in the test file declare a "human readable ABI" as defined in the [ethers documentation](https://docs.ethers.io/v5/api/utils/abi/interface/#Interface--creating)

The following is an example of how this may look.

```js
const daiABI = [
    "function approve(address,address,uint256) returns (bool)",
    "function mint(address,uint256)"
]

dai = new ethers.Contract(daiAddress, daiABI, accounts[0])
```

This will greatly reduce ABI bloat.

**Comment by saflamini** [comment]
@JoshuaTrujillo15 

NATSPEC comments added for all functions, state vars
DAI abi file removed, lightweight pattern from ethers.js adopted for testing

**Review by JoshuaTrujillo15 — CHANGES_REQUESTED** [review]
# Code Review

## Contracts

Natspec comments are missing tags, please update.

https://docs.soliditylang.org/en/v0.8.15/natspec-format.html#natspec

See [this contract](https://github.com/superfluid-finance/super-examples/blob/main/examples/stream-in-distribute-out/contracts/base/StreamInDistributeOut.sol) as an example.

**Comment by saflamini** [comment]
Natspec tags added

**Review by JoshuaTrujillo15 — APPROVED** [review]
LGTM 🤘

**Pull request merged**
